name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PSNetworkVapor merge to main using ${{ matrix.swift }} on ${{ matrix.os }}
    strategy: 
      matrix:
        os: [macos-latest]
        swift: ["5.8"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: swift-actions/setup-swift@v1
      with: 
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v3
    - name: Swiftlint
      run: swiftlint lint
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
